export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";

export const SET_INGREDIENTS_SUCCESS = "SET_INGREDIENTS_SUCCESS";
export const SET_INGREDIENTS_FAIL = "SET_INGREDIENTS_FAIL";

export const BURGER_ORDER_INIT = "BURGER_ORDER_INIT";
export const BURGER_ORDER_SUCCESS = "BURGER_ORDER_SUCCESS";
export const BURGER_ORDER_FAIL = "BURGER_ORDER_FAIL";

export const FETCH_ORDERS_INIT = "FETCH_ORDERS_INIT";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";

export const PURCHASE_END = "PURCHASE_END";
